name: 'CI'
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      compiler-ref:
        type: string
jobs:
  find-latest-release:
    uses: lf-lang/lingua-franca/.github/workflows/latest-release.yml@master
    if: ${{ inputs.compiler-ref == '' }}

  check-compile:
    runs-on: ubuntu-latest
    needs: find-latest-release
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Java 17
        run: |
          echo "$JAVA_HOME_17_X64/bin" >> $GITHUB_PATH
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
        shell: bash
      - name: Install dev dependencies
        run: |
          sudo apt update
          sudo apt install cmake make gcc gcc-arm-none-eabi libnewlib-arm-none-eabi
      - uses: lf-lang/action-check-lf-files@main
        with:
          check_mode: "compile"
          no_compile_flag: false
          exclude_dirs: '["failing", "experimental"]'
          checkout_dir: '../lingua-franca'
          compiler_ref: ${{ inputs.compiler-ref || needs.find-latest-release.outputs.ref }}

  check-format:
    runs-on: ubuntu-latest
    needs: find-latest-release
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 17
        run: |
          echo "$JAVA_HOME_17_X64/bin" >> $GITHUB_PATH
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
        shell: bash
      - uses: lf-lang/action-check-lf-files@main
        with:
          check_mode: "format"
          exclude_dirs: '["failing", "experimental"]'
          checkout_dir: '../lingua-franca'
          compiler_ref: ${{ inputs.compiler-ref || needs.find-latest-release.outputs.ref }}
